# Payments Transactional PostgreSQL DB
# This database stores transactions, payment links, Mercado Pago notifications, etc.

FROM postgres:16-alpine

# Copy init scripts
COPY init/ /docker-entrypoint-initdb.d/