"""Prompts package for both admin and customer services."""
from agents.prompt.admin import (
    PROMPT_GUARD,
    PROMPT_IDENTIFIER,
    PROMPT_NEXUS,
    PROMPT_QUERY,
    PROMPT_KNOWLEDGE,
    PROMPT_PAYMENT,
    PROMPT_WRITER,
    PROMPT_LLM_ADMIN,
)
from agents.prompt.customer import (
    PROMPT_GUARD as PROMPT_GUARD_CUSTOMER,
    PROMPT_IDENTIFIER as PROMPT_IDENTIFIER_CUSTOMER,
    PROMPT_NEXUS as PROMPT_NEXUS_CUSTOMER,
    PROMPT_QUERY as PROMPT_QUERY_CUSTOMER,
    PROMPT_KNOWLEDGE as PROMPT_KNOWLEDGE_CUSTOMER,
    PROMPT_PAYMENT as PROMPT_PAYMENT_CUSTOMER,
    PROMPT_WRITER as PROMPT_WRITER_CUSTOMER,
    PROMPT_LLM_HUESPED,
)

__all__ = [
    "PROMPT_GUARD",
    "PROMPT_IDENTIFIER",
    "PROMPT_NEXUS",
    "PROMPT_QUERY",
    "PROMPT_KNOWLEDGE",
    "PROMPT_PAYMENT",
    "PROMPT_WRITER",
    "PROMPT_LLM_ADMIN",
    "PROMPT_LLM_HUESPED",
    "PROMPT_GUARD_CUSTOMER",
    "PROMPT_IDENTIFIER_CUSTOMER",
    "PROMPT_NEXUS_CUSTOMER",
    "PROMPT_QUERY_CUSTOMER",
    "PROMPT_KNOWLEDGE_CUSTOMER",
    "PROMPT_PAYMENT_CUSTOMER",
    "PROMPT_WRITER_CUSTOMER",
]